appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: zDjFQgHZEzSbHGrz2dDFr+oL75Mz4YHfuf9vRvjXxOItS5R9zlYGU5cJdy9oH3V8upQCwZDhq3gDWX5AaNHTvKzDr0wtC9EqkGPx6SnbHcZEDnseIrO7+jEyaFeTREoKOMC4O9vdak7ywAZrrmbpEnsEiUugG9zHjE9+hbmQh7IOE80MaccXd/EQYYonwYcM22DF+P8PK7ao1FHSw7iC6rSVXorI0acDzse7deqUvWvZSqG+TVS/qUDLPzTR2WvVTBtmoEfo5fR058J6RlGRJJlT2nU4RIbOV5xt5nLOTLHX0MB3CDtY7PY2KJgfTgCz1+2Twc/t4pGBSuKoEXS5Z4/HsRLyRm9UMaHiLln5Uudx9fqDFHt1Y0Y5cpF43F7gMhLKUxpvvFTrHc9DTB8ZCjav0BrtHegPm8cIfKU++JLAcyXVO4FtG1KQVtmwf8dsVvYpbZDkgw+0sOhPHqhFAfEgOpcjAODyaA7Fm9QgrWSemOVagU5BpIu4tqTQpEt/bJS5kV1ccwLUPR75C+340keu8X5KyNcVT7AHOq8jyNmEpgwrkSlYmA/vt6hbUM0cGh/0RuSF1wOkM4ImrERDlPqQlm7hp/b1V0Za+XBXE+QniCJr0UdyX5NJSIeHgBU5U/U5LGnAx9Pb7ngmtMDLN90ixfpED+yZoKxdNAS1tPA=}
bot:
  automerge: true
